Fixed marshmallow error reporting
socialwifi/flask-jsonapi pull request #44
Opened 2019-08-08 09:39 UTC by riklaunim

2019-08-13 15:00 UTC, Behoston requested changes

2019-08-13 15:00 UTC, Behoston commented on flask_jsonapi/resources.py
> +            raise exceptions.JsonApiException(detail=str(e), source={'component': 'schema'})
I'm not sure if we should return whole error as detail

2019-08-13 15:00 UTC, Behoston commented on setup.py
> -    version='0.10.1.dev0',
Leave 
`     version='0.10.1.dev0',`
releasing tool can handle versioning.

2019-08-13 15:02 UTC, riklaunim commented on flask_jsonapi/resources.py
> +            raise exceptions.JsonApiException(detail=str(e), source={'component': 'schema'})
it happens during development and there it's very helpful.

2019-08-13 15:02 UTC, riklaunim commented on setup.py
> -    version='0.10.1.dev0',
ok

2019-09-17 08:59 UTC, jgoclawski commented
LGTM :+1:

2019-09-17 08:59 UTC, jgoclawski approved these changes

2019-09-17 09:00 UTC, merged